name: sea-temperatures-card-test
services:
  homeassistant:
    container_name: ha-sea-temperatures-card-test
    image: homeassistant/home-assistant:stable
    volumes:
      - ./test_config:/config
      - ./custom_components/seatemperatures:/config/custom_components/seatemperatures
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8125:8123'
    restart: unless-stopped
    privileged: true
